### ISSUE TITLE
ValueError: attempt to get argmax of an empty sequence

### ISSUE THREAD

**Issue by mikegerber** [qurator-spk/column_classifier_tool#5]
~~~
2022-02-11 16:45:22 sbb_column_classifier DEBUG    Running for /srv/digisam_images/sbb/PPN841204047/00000002.tif...
Traceback (most recent call last):
  File "/home/mike/devel/column_classifier_tool/sbb_column_classifier/sbb_column_classifier.py", line 347, in process
    cl.run(image_file)
  File "/home/mike/devel/column_classifier_tool/sbb_column_classifier/sbb_column_classifier.py", line 299, in run
    image_page, _ = self.extract_page(image_file)
  File "/home/mike/devel/column_classifier_tool/sbb_column_classifier/sbb_column_classifier.py", line 261, in extract_page
    cnt = contours[np.argmax(cnt_size)]
  File "<__array_function__ internals>", line 6, in argmax
  File "/home/mike/.virtualenvs/column_classifier_tool/lib64/python3.6/site-packages/numpy/core/fromnumeric.py", line 1186, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out)
  File "/home/mike/.virtualenvs/column_classifier_tool/lib64/python3.6/site-packages/numpy/core/fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
ValueError: attempt to get argmax of an empty sequence
~~~

**Comment by mikegerber** [comment]
It's easily reproduced with the attached image file (converted to PNG for GitHub, same error as with the original TIFF image).

~~~
% sbb_column_classifier --model ~/devel/qurator-data/eynollah 00000002.tif.png
2022-02-17 14:28:38 sbb_column_classifier DEBUG    Loading model model_scale_classifier.h5...
2022-02-17 14:28:44 sbb_column_classifier DEBUG    Loading model done.
2022-02-17 14:28:44 sbb_column_classifier DEBUG    Loading model model_page_mixed_best.h5...
2022-02-17 14:28:50 sbb_column_classifier DEBUG    Loading model done.
2022-02-17 14:28:50 sbb_column_classifier DEBUG    Running for 00000002.tif.png...
Traceback (most recent call last):
  File "/home/mike/devel/sbb_column_classifier/sbb_column_classifier/sbb_column_classifier.py", line 348, in process
    cl.run(image_file)
  File "/home/mike/devel/sbb_column_classifier/sbb_column_classifier/sbb_column_classifier.py", line 314, in run
    image_page, _ = self.extract_page(image_file)
  File "/home/mike/devel/sbb_column_classifier/sbb_column_classifier/sbb_column_classifier.py", line 276, in extract_page
    cnt = contours[np.argmax(cnt_size)]
  File "<__array_function__ internals>", line 6, in argmax
  File "/home/mike/.virtualenvs/sbb_column_classifier/lib64/python3.6/site-packages/numpy/core/fromnumeric.py", line 1186, in argmax
    return _wrapfunc(a, 'argmax', axis=axis, out=out)
  File "/home/mike/.virtualenvs/sbb_column_classifier/lib64/python3.6/site-packages/numpy/core/fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
ValueError: attempt to get argmax of an empty sequence
~~~
![00000002 tif](https://user-images.githubusercontent.com/34309482/154491570-913b4eb5-fa9e-419b-8a95-6aabc4989a84.png)

**Comment by cneud** [comment]
Interesting that this keeps happening, as a fix for the same issue in Eynollah was supplied [here](https://github.com/qurator-spk/eynollah/commit/43c93023908f61f9283b3a91ed51b2cf56ea6ed1).

**Comment by mikegerber** [comment]
This comes with code duplication... That part of the code seems to be for detection of the border or the print space and it's in eynollah too.

(Other parts like the [very very mysterious code for ... I don't know for sure... padding?](https://github.com/qurator-spk/sbb_column_classifier/blob/master/sbb_column_classifier/sbb_column_classifier.py#L130-L223) is in 3 projects now.)

**Comment by mikegerber** [comment]
I ported the fix from the diff above.
